Repository 5G-ERA/middleware, pull requests merged in 2023-04, with the labels that each got.

#137 Change the default image registry for the Middleware images
  docs/Administrator/Actionserver.md
  docs/Administrator/Middleware_Installation.md
  docs/Administrator/readme.md
  docs/Where_to_start/roadmap.md
  k8s/central-api/central-api.yaml
  k8s/gateway/gateway_deployment.yaml
  k8s/orchestrator/orchestrator.yaml
  k8s/redis-interface/redis_interface_deployment.yaml
  k8s/task-planner/task_planner_deployment.yaml
  src/Orchestrator/Deployment/DeploymentService.cs
  src/RedisInterface.Sdk/IRedisInterfaceClient.cs
Labels: documentation, enhancement

#141 Edge and Cloud onboarding corrections
  OpenAPISpec.json
  docs/User/Onboarding/Edge Onboarding.md
  docs/User/Onboarding/img/EdgeTemplate.jpg
  docs/User/Onboarding/img/OnboardedEdge.png
  src/CentralApi/Mappings/ApiContractToDomainMapper.cs
  src/CentralApi/Services/LocationService.cs
  src/CentralApi/Validation/RegisterRequestValidator.cs
  src/DataAccess/Repositories/Redis/RedisCloudRepository.cs
  src/DataAccess/Repositories/Redis/RedisEdgeRepository.cs
  src/Models/Domain/CloudModel.cs
  src/Models/Domain/EdgeModel.cs
  src/Models/Dto/CloudDto.cs
  src/Models/Dto/EdgeDto.cs
  src/Models/Enums/LocationType.cs
  src/Orchestrator/Deployment/DeploymentService.cs
  src/RedisInterface.Contracts/Mappings/ApiContractToDomainMapper.cs
  src/RedisInterface.Contracts/Mappings/DomainToApiContractMapper.cs
  src/RedisInterface.Contracts/Requests/CloudRequest.cs
  src/RedisInterface.Contracts/Requests/EdgeRequest.cs
  src/RedisInterface.Contracts/Responses/CloudResponse.cs
  src/RedisInterface.Contracts/Responses/EdgeResponse.cs
  src/RedisInterface/Mappings/ApiContractToDomainMapper.cs
  src/RedisInterface/RedisInterfaceSpec.json
  src/RedisInterface/Validation/CloudRequestValidator.cs
  src/RedisInterface/Validation/EdgeRequestValidator.cs
  test/CentralApi.Tests.Unit/Services/LocationServiceTests.cs
Labels: bug, documentation

#138 Fix display of the robot properties
  src/Models/Domain/ROSNodeModel.cs
  src/Models/Domain/SensorModel.cs
  src/Models/Dto/RobotDto.cs
  src/Models/Dto/Ros/RosNode.cs
  src/Models/Dto/Ros/RosService.cs
  src/Models/Dto/Ros/Sensor.cs
Labels: bug

#142 81 rbac changes to the middleware
  src/DataAccess/HostedServices/IndexCreationService.cs
  src/DataAccess/Repositories/Abstract/IUserRepository.cs
  src/DataAccess/Repositories/UserRepository.cs
  src/Models/Domain/UserModel.cs
  src/Models/Dto/UserDto.cs
  src/OcelotGateway/Contracts/LoginRequest.cs
  src/OcelotGateway/Contracts/Mappings.cs
  src/OcelotGateway/Contracts/RegisterRequest.cs
  src/OcelotGateway/Contracts/RegisterResponse.cs
  src/OcelotGateway/Controllers/LoginController.cs
  src/OcelotGateway/OcelotGateway.csproj
  src/OcelotGateway/Program.cs
  src/OcelotGateway/Services/OcelotAuthorizationMiddleware.cs
  src/OcelotGateway/Services/RoleClaimAuthorizer.cs
  src/OcelotGateway/Services/ServiceCollectionExtensions.cs
  src/OcelotGateway/Services/TokenService.cs
  src/OcelotGateway/ocelot.Development.json
  src/OcelotGateway/ocelot.Production.json
  src/RedisInterface/Program.cs
Labels: enhancement
