Repository 5G-ERA/middleware, pull requests merged in 2023-06, with the labels that each got.

#163 Remove the inactive ActionPlans
  Middleware.sln.DotSettings
  src/Common/Enums/ServiceStatus.cs
  src/DataAccess/Repositories/InstanceRepository.cs
  src/DataAccess/Repositories/Redis/RedisInstanceRepository.cs
  src/Models/Domain/InstanceModel.cs
  src/Models/Dto/InstanceDto.cs
  src/Models/Enums/ServiceStatus.cs
  src/Orchestrator/Deployment/DeploymentService.cs
  src/Orchestrator/Jobs/BaseJob.cs
  src/Orchestrator/Jobs/UpdateStatusJob.cs
Labels: bug

#165 Slice Manager integration corrections
  src/Common/MessageContracts/ConnectRobotToSliceMessage.cs
  src/DataAccess/Repositories/Abstract/ICloudRepository.cs
  src/DataAccess/Repositories/Abstract/IEdgeRepository.cs
  src/DataAccess/Repositories/Abstract/ISliceRepository.cs
  src/DataAccess/Repositories/CloudRepository.cs
  src/DataAccess/Repositories/EdgeRepository.cs
  src/Models/Dto/Slice/SliceDto.cs
  src/OcelotGateway/ocelot.Development.json
  src/OcelotGateway/ocelot.Production.json
  src/Orchestrator/Handlers/Slice/ConnectRobotToSliceConsumer.cs
  src/Orchestrator/SliceManager/ISliceManager.cs
  src/Orchestrator/SliceManager/SliceManager.cs
  src/Orchestrator/SliceManager/SliceManagerClientFactory.cs
  src/RedisInterface.Contracts/Mappings/ApiContractToDomainMapper.cs
  src/RedisInterface.Contracts/Mappings/DomainToApiContractMapper.cs
  src/RedisInterface.Sdk/Client/IRedisInterface.cs
  src/RedisInterface.Sdk/IRedisInterfaceClient.cs
  src/RedisInterface.Sdk/RedisInterfaceClient.cs
  src/RedisInterface/Controllers/SliceController.cs
  src/RedisInterface/Services/Abstract/ISliceService.cs
  src/RedisInterface/Services/SliceService.cs
  src/TaskPlanner/Services/Abstract/IPublishService.cs
  src/TaskPlanner/Services/PublishingService.cs
  test/Orchestrator.Tests.Unit/SliceManager/SliceManagerClientFactoryTests.cs
  test/RedisInterface.Tests.Unit/Services/SliceServiceTests.cs
Labels: bug, enhancement

#170 Deleted unused API references
  src/Orchestrator/ApiReference/Abstract/IApiClientBuilder.cs
  src/Orchestrator/ApiReference/ApiClientBuilder.cs
  src/Orchestrator/ApiReference/OsmClient.cs
  src/Orchestrator/ApiReference/Specification/OsmOpenApiSpec.json
  src/Orchestrator/ApiReference/Specification/OsmOpenApiSpec.yaml
  src/Orchestrator/ApiReference/Specification/sanitizeOsmSpec.py
  src/Orchestrator/Deployment/DeploymentService.cs
  src/Orchestrator/Jobs/MiddlewareStartupJob.cs
  src/Orchestrator/Jobs/UpdateStatusJob.cs
  src/Orchestrator/Orchestrator.csproj
  src/Orchestrator/Program.cs
  src/RedisInterface.Sdk/RedisInterfaceClient.cs
  src/ResourcePlanner/Config/AutoMapperConfig.cs
  src/ResourcePlanner/Controllers/ReplanResourceController.cs
  src/ResourcePlanner/Controllers/ResourceController.cs
  src/ResourcePlanner/ResourcePlanner.csproj
  src/TaskPlanner/ApiReference/ApiClientBuilder.cs
  src/TaskPlanner/ApiReference/NSwagClientError_Missing_Code_Generation_Of_ApiException_OnTheSecondClient.cs
  src/TaskPlanner/Config/AutoMapperConfig.cs
  src/TaskPlanner/Controllers/PlanController.cs
  src/TaskPlanner/Controllers/RePlanController.cs
  src/TaskPlanner/TaskPlanner.csproj
Labels: bug

#171 Orchestrator - Single Action NetApps visibility
  Middleware.sln.DotSettings
  docs/Administrator/NetworkApplicationCommunication.md
  src/Common/Config/AppConfig.cs
  src/Common/Enums/K8SServiceKind.cs
  src/Common/ExtensionMethods/KubernetesObjectExtensions.cs
  src/Common/ExtensionMethods/StringExtensions.cs
  src/Models/Domain/ActionPlanModel.cs
  src/Models/Dto/ActionPlanDto.cs
  src/Orchestrator/Controllers/OrchestrateController.cs
  src/Orchestrator/Deployment/Abstract/IDeploymentService.cs
  src/Orchestrator/Deployment/Abstract/IKubernetesObjectBuilder.cs
  src/Orchestrator/Deployment/DeploymentService.cs
  src/Orchestrator/Deployment/KubernetesBuilder.cs
  src/Orchestrator/Deployment/KubernetesObjectBuilder.cs
  src/Orchestrator/Handlers/DeployPlan/DeployPlanConsumer.cs
  src/Orchestrator/Jobs/MiddlewareStartupJob.cs
  src/Orchestrator/Jobs/UpdateStatusJob.cs
  src/Orchestrator/Models/DeploymentPair.cs
  src/Orchestrator/Models/DeploymentPairModel.cs
  src/Orchestrator/Orchestrator.csproj
  src/Orchestrator/Program.cs
  test/Orchestrator.Tests.Unit/Deployment/KubernetesObjectBuilderTests.cs
  test/Orchestrator.Tests.Unit/KubernetesBuilderTests.cs
  test/Orchestrator.Tests.Unit/Orchestrator.Tests.Unit.csproj
Labels: enhancement

#173 ROS1 Communication Support
  Middleware.sln.DotSettings
  docs/Administrator/ImportTaskTemplates/teleoperation-deployment.yaml
  docs/Administrator/ImportTaskTemplates/teleoperation-service.yaml
  docs/Administrator/ImportTaskTemplates/teleoperation.json
  src/Models/Domain/RosDistro.cs
  src/Models/Enums/RosDistro.cs
  src/Models/Exceptions/IncorrectRosDistroNameException.cs
  src/Orchestrator/Controllers/HealthController.cs
  src/Orchestrator/Controllers/OrchestrateController.cs
  src/Orchestrator/Controllers/StatusController.cs
  src/Orchestrator/Deployment/Abstract/IRosConnectionBuilder.cs
  src/Orchestrator/Deployment/Abstract/IRosConnectionBuilderFactory.cs
  src/Orchestrator/Deployment/DeploymentService.cs
  src/Orchestrator/Deployment/KubernetesObjectBuilder.cs
  src/Orchestrator/Deployment/RosCommunication/Ros1ConnectionBuilder.cs
  src/Orchestrator/Deployment/RosCommunication/Ros2ConnectionBuilder.cs
  src/Orchestrator/Deployment/RosConnectionBuilderFactory.cs
  src/Orchestrator/Jobs/UpdateStatusJob.cs
  src/RedisInterface/Validation/InstanceRequestValidator.cs
  src/RedisInterface/Validation/RobotRequestValidator.cs
  test/Orchestrator.Tests.Unit/Deployment/Ros1ConnectionBuilderTests.cs
  test/Orchestrator.Tests.Unit/Deployment/RosConnectionBuilderFactoryTests.cs
  test/Orchestrator.Tests.Unit/Orchestrator.Tests.Unit.csproj
Labels: bug, enhancement

#174 134 dynamic gateway reconfiguration
  docs/Administrator/Gateway/readme.md
  src/Common/Helpers/QueueHelpers.cs
  src/Common/MessageContracts/GatewayAddNetAppEntryMessage.cs
  src/Common/MessageContracts/GatewayDeleteNetAppEntryMessage.cs
  src/OcelotGateway/ExtensionMethods/ServiceCollectionExtensions.cs
  src/OcelotGateway/Handlers/CreateDynamicRouteConsumer.cs
  src/OcelotGateway/Handlers/DeleteDynamicRouteConsumer.cs
  src/OcelotGateway/OcelotGateway.csproj
  src/OcelotGateway/Program.cs
  src/OcelotGateway/Services/GatewayConfigurationService.cs
Labels: enhancement
