Repository 5G-ERA/middleware, pull requests merged in 2023-12, with the labels that each got.

#241 feat: heartbeat for robot-location can_reach relation and cron done
  src/CentralApi.Contracts/Responses/RelationToLocationRequest.cs
  src/CentralApi/Controllers/RobotController.cs
  src/CentralApi/ExtensionMethods/QuartExtension2.cs
  src/CentralApi/Jobs/UpdateOnlineLocationJob.cs
  src/CentralApi/Program.cs
  src/CentralApi/Services/Abstract/IRobotService.cs
  src/CentralApi/Services/RobotService.cs
  src/DataAccess/DataAccess.csproj
  src/DataAccess/ExtensionMethods/DataAccessExtensionMethods.cs
  src/DataAccess/HostedServices/IndexCreationService.cs
  src/DataAccess/Repositories/Abstract/ILocationRepository.cs
  src/DataAccess/Repositories/Abstract/IRelationRepository.cs
  src/DataAccess/Repositories/BaseRepository.cs
  src/DataAccess/Repositories/Redis/RedisLocationRepository.cs
  src/DataAccess/Repositories/RedisRepository.cs
Labels: enhancement

#245 feat: configure properties to accept value ranges
  src/CentralApi.Sdk/CentralApiClient.cs
  src/DataAccess/HostedServices/IndexCreationService.cs
  src/DataAccess/Repositories/ActionPlanRepository.cs
  src/DataAccess/Repositories/Redis/RedisInstanceRepository.cs
  src/DataAccess/Repositories/RedisRepository.cs
  src/Models/Domain/ActionModel.cs
  src/Models/Domain/ActuatorModel.cs
  src/Models/Domain/CloudEdgeStatusResponse.cs
  src/Models/Domain/DialogueModel.cs
  src/Models/Domain/GraphEntityModel.cs
  src/Models/Domain/InstanceModel.cs
  src/Models/Domain/KeyValuePair.cs
  src/Models/Domain/ManipulatorModel.cs
  src/Models/Domain/Osm/VnfPkgInfoModel.cs
  src/Models/Domain/RelationModel.cs
  src/Models/Domain/RobotModel.cs
  src/Models/Domain/Status/NetAppStatusModel.cs
  src/Models/Domain/Status/RobotStatusModel.cs
  src/Models/Domain/TaskModel.cs
  src/Models/Domain/UserModel.cs
  src/Models/Domain/ValueObjects/NetAppRequirement.cs
  src/Models/Dto/ActionDto.cs
  src/Models/Dto/CloudDto.cs
  src/Models/Dto/DialogueDto.cs
  src/Models/Dto/EdgeDto.cs
  src/Models/Dto/Hardware/HardwareRequirements.cs
  src/Models/Dto/InstanceDto.cs
  src/Models/Dto/LocationDto.cs
  src/Models/Dto/NetAppStatusDto.cs
  src/Models/Dto/PolicyDto.cs
  src/Models/Dto/RobotDto.cs
  src/Models/Dto/RobotStatusDto.cs
  src/Models/Dto/Ros/Actuator.cs
  src/Models/Dto/Ros/Manipulator.cs
  src/Models/Dto/TaskDto.cs
  src/Models/Enums/ResourcePriority.cs
  src/Models/Models.csproj
  src/RedisInterface.Contracts/Mappings/ApiContractToDomainMapper.cs
  src/RedisInterface.Contracts/Mappings/DomainToApiContractMapper.cs
  src/RedisInterface.Contracts/Requests/ContainerRequest.cs
  src/RedisInterface.Contracts/Requests/InstanceRequest.cs
  src/RedisInterface.Contracts/Requests/RequirementRequest.cs
  src/RedisInterface.Contracts/Requests/RobotRequest.cs
  src/RedisInterface.Contracts/Responses/ContainerResponse.cs
  src/RedisInterface.Contracts/Responses/FullTaskResponse.cs
  src/RedisInterface.Contracts/Responses/InstanceResponse.cs
  src/RedisInterface.Contracts/Responses/RequirementResponse.cs
  src/RedisInterface.Contracts/Responses/RobotResponse.cs
  src/RedisInterface.Contracts/Responses/UpdateTopicResponse.cs
  src/RedisInterface/Mappings/ApiContractToDomainMapper.cs
  src/ResourcePlanner/ResourcePlanner.cs
Labels: enhancement

#247 200 https and tls termination in middleware
  docs/Administrator/TLS_Configuration/TLS_Configuration.md
Labels: documentation, enhancement

#250 docs: https and tls termination in middleware
  docs/Administrator/TLS_Configuration/TLS_Configuration.md
Labels: documentation, enhancement

#249 feat: change property name for enabling/disabling resource reuse
  src/DataAccess/Repositories/Redis/RedisTaskRepository.cs
  src/Models/Domain/TaskModel.cs
  src/ResourcePlanner/ResourcePlanner.cs
  src/TaskPlanner/Contracts/Requests/CreatePlanRequest.cs
  src/TaskPlanner/Contracts/Requests/CreateRePlanRequest.cs
  src/TaskPlanner/Controllers/PlanController.cs
  src/TaskPlanner/Services/ActionPlanner.cs
Labels: bug, enhancement

#217 chore(main): release 0.8.0
  CHANGELOG.md
Labels: autorelease: pending
