Repository 5G-ERA/middleware, pull requests merged in 2023-05, with the labels that each got.

#146 Updated remaining Dto's with index recreation
  src/DataAccess/HostedServices/IndexCreationService.cs
Labels: bug

#148 Kubernetes version bump and package versions consolidation
  src/CentralApi/CentralApi.csproj
  src/Common/Common.csproj
  src/OcelotGateway/OcelotGateway.csproj
  src/Orchestrator/Orchestrator.csproj
  src/RedisInterface/RedisInterface.csproj
  src/ResourcePlanner/ResourcePlanner.csproj
  src/TaskPlanner/TaskPlanner.csproj
  test/Common.Tests.Unit/Common.Tests.Unit.csproj
  test/DataAccess.Tests.Unit/DataAccess.Tests.Unit.csproj
  test/Orchestrator.Tests.Unit/Orchestrator.Tests.Unit.csproj
  test/RedisInterface.Sdk.Tests.Integration/RedisInterface.Sdk.Tests.Integration.csproj
Labels: bug, enhancement

#149 116 cloud infrastructure definition
  .gitignore
  docs/Administrator/readme.md
  terraform/AWS/.terraform.lock.hcl
  terraform/AWS/README.md
  terraform/AWS/main.tf
  terraform/AWS/modules/infrastructure/elb.tf
  terraform/AWS/modules/infrastructure/main.tf
  terraform/AWS/modules/infrastructure/outputs.tf
  terraform/AWS/modules/infrastructure/policy.tf
  terraform/AWS/modules/infrastructure/variables.tf
  terraform/AWS/modules/infrastructure/versions.tf
  terraform/AWS/modules/k8s-config/main.tf
  terraform/AWS/modules/k8s-config/outputs.tf
  terraform/AWS/modules/k8s-config/variables.tf
  terraform/AWS/modules/k8s-config/versions.tf
  terraform/AWS/outputs.tf
  terraform/AWS/variables.tf
Labels: documentation, enhancement

#150 Models properties adjustment for better consistency
  src/DataAccess/Repositories/ActionRepository.cs
  src/DataAccess/Repositories/Redis/RedisActionRepository.cs
  src/Models/Domain/ActionModel.cs
  src/Models/Domain/ActionPlanModel.cs
  src/Models/Domain/ActuatorModel.cs
  src/Models/Domain/CloudModel.cs
  src/Models/Domain/ContainerImageModel.cs
  src/Models/Domain/DialogueModel.cs
  src/Models/Domain/EdgeModel.cs
  src/Models/Domain/GraphEntityModel.cs
  src/Models/Domain/InstanceModel.cs
  src/Models/Domain/ManipulatorModel.cs
  src/Models/Domain/Osm/VnfPkgInfoModel.cs
  src/Models/Domain/PolicyModel.cs
  src/Models/Domain/RobotModel.cs
  src/Models/Domain/RosTopicModel.cs
  src/Models/Domain/SensorModel.cs
  src/Models/Domain/SliceModel.cs
  src/Models/Domain/Status/NetAppStatusModel.cs
  src/Models/Domain/Status/RobotStatusModel.cs
  src/Models/Domain/TaskModel.cs
  src/Models/Domain/TokenModel.cs
  src/Models/Domain/UserModel.cs
  src/Models/Dto/ActionDto.cs
  src/Models/Dto/ActionPlanDto.cs
  src/Models/Dto/CloudDto.cs
  src/Models/Dto/ContainerImageDto.cs
  src/Models/Dto/DialogueDto.cs
  src/Models/Dto/EdgeDto.cs
  src/Models/Dto/Hardware/HardwareRequirements.cs
  src/Models/Dto/Hardware/HardwareSpec.cs
  src/Models/Dto/InstanceDto.cs
  src/Models/Dto/NetAppStatusDto.cs
  src/Models/Dto/PolicyDto.cs
  src/Models/Dto/RobotDto.cs
  src/Models/Dto/RobotStatusDto.cs
  src/Models/Dto/Ros/Actuator.cs
  src/Models/Dto/Ros/Manipulator.cs
  src/Models/Dto/Ros/RosInfo.cs
  src/Models/Dto/Ros/RosNode.cs
  src/Models/Dto/Ros/Sensor.cs
  src/Models/Dto/TaskDto.cs
  src/Models/Dto/UserDto.cs
  src/RedisInterface.Contracts/Responses/ActionResponse.cs
Labels: bug
